steps:
  build:
    image: gradle:8.8-jdk11
    when:
      branch: main
    commands:
      - git checkout $CI_COMMIT_BRANCH
      # Code works
      - gradle test
      # Code is clean
      - gradle check javadocAll
      # Code has coverage
      - gradle jacocoRootReport coveralls
    environment:
      COVERALLS_REPO_TOKEN:
        from_secret: COVERALLS_REPO_TOKEN
